import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Tenant } from '../../../common/entities/tenant.entity';

/**
 * Projection of {@link Tenant} returned by {@link TenantStore}.
 *
 * Deliberately omits `encryption_key`: the per-tenant data-encryption key is a
 * server-side secret and must never cross the store boundary toward callers.
 */
export interface StoredTenant {
  id: string;
  name: string;
  region: string;
  branding: Record<string, any> | null;
  settings: Record<string, any>;
  metadata: Record<string, any> | null;
  adminEmail: string | null;
  planId: string | null;
  billingEmail: string | null;
  tier: string | null;
  createdAt: Date;
  updatedAt: Date;
}

/** Fields a caller may patch on an existing tenant. All optional. */
export interface TenantPatch {
  name?: string;
  region?: string;
  branding?: Record<string, any> | null;
  settings?: Record<string, any>;
  metadata?: Record<string, any> | null;
  adminEmail?: string | null;
  planId?: string | null;
  billingEmail?: string | null;
  tier?: string | null;
}

/**
 * Data-access facade for {@link Tenant} records.
 *
 * Read methods rely on TypeORM soft-delete semantics: rows with a non-null
 * `deletedAt` are excluded automatically, so a soft-deleted tenant is invisible
 * to {@link findById}, {@link findByName}, and {@link findAll}.
 */
@Injectable()
export class TenantStore {
  constructor(
    @InjectRepository(Tenant)
    private readonly repo: Repository<Tenant>,
  ) {}

  /**
   * Persist a new tenant. The `encryptionKey` is generated by the caller
   * (see {@link TenantService}) and stored verbatim; it is never returned.
   */
  async create(params: {
    name: string;
    encryptionKey: string;
    region?: string;
    branding?: Record<string, any> | null;
    settings?: Record<string, any>;
    metadata?: Record<string, any> | null;
    adminEmail?: string | null;
    planId?: string | null;
    billingEmail?: string | null;
    tier?: string | null;
  }): Promise<StoredTenant> {
    const tenant = this.repo.create({
      name: params.name,
      encryption_key: params.encryptionKey,
      region: params.region ?? 'local',
      branding: params.branding ?? null,
      settings: params.settings ?? {},
      metadata: params.metadata ?? null,
      adminEmail: params.adminEmail ?? null,
      planId: params.planId ?? null,
      billingEmail: params.billingEmail ?? null,
      tier: params.tier ?? null,
    });

    const saved = await this.repo.save(tenant);
    return this.toStored(saved);
  }

  /** Look up a tenant by its primary-key UUID. */
  async findById(id: string): Promise<StoredTenant | undefined> {
    const tenant = await this.repo.findOneBy({ id });
    return tenant ? this.toStored(tenant) : undefined;
  }

  /** Look up a tenant by its unique (case-insensitive) name. */
  async findByName(name: string): Promise<StoredTenant | undefined> {
    const tenant = await this.repo.findOneBy({ name });
    return tenant ? this.toStored(tenant) : undefined;
  }

  /** Return every tenant, newest first. */
  async findAll(): Promise<StoredTenant[]> {
    const tenants = await this.repo.find({ order: { createdAt: 'DESC' } });
    return tenants.map((t) => this.toStored(t));
  }

  /**
   * Apply a partial update to an existing tenant. Only defined keys on `patch`
   * are written; `undefined` values are ignored so unspecified fields keep
   * their current values.
   *
   * @throws NotFoundException when the tenant id does not exist.
   */
  async update(id: string, patch: TenantPatch): Promise<StoredTenant> {
    const tenant = await this.repo.findOneBy({ id });
    if (!tenant) {
      throw new NotFoundException({ error: 'tenant_not_found' });
    }

    if (patch.name !== undefined) tenant.name = patch.name;
    if (patch.region !== undefined) tenant.region = patch.region;
    if (patch.branding !== undefined) tenant.branding = patch.branding;
    if (patch.settings !== undefined) tenant.settings = patch.settings;
    if (patch.metadata !== undefined) tenant.metadata = patch.metadata;
    if (patch.adminEmail !== undefined) tenant.adminEmail = patch.adminEmail;
    if (patch.planId !== undefined) tenant.planId = patch.planId;
    if (patch.billingEmail !== undefined) tenant.billingEmail = patch.billingEmail;
    if (patch.tier !== undefined) tenant.tier = patch.tier;

    const saved = await this.repo.save(tenant);
    return this.toStored(saved);
  }

  /**
   * Soft-delete a tenant by stamping `deletedAt`. The row is retained for
   * audit/recovery but excluded from all subsequent reads.
   *
   * @throws NotFoundException when the tenant id does not exist (or is already deleted).
   */
  async softDelete(id: string): Promise<void> {
    const result = await this.repo.softDelete({ id });
    if (!result.affected) {
      throw new NotFoundException({ error: 'tenant_not_found' });
    }
  }

  /** Map a TypeORM entity to the public {@link StoredTenant} projection. */
  private toStored(entity: Tenant): StoredTenant {
    return {
      id: entity.id,
      name: entity.name,
      region: entity.region,
      branding: entity.branding,
      settings: entity.settings,
      metadata: entity.metadata,
      adminEmail: entity.adminEmail,
      planId: entity.planId,
      billingEmail: entity.billingEmail,
      tier: entity.tier,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
    };
  }
}
